* YOUSOFTMATTER.ORG
* Instructions
** Hugo command
*** Real-time editing
    Run /hugo server/ in the hugo root directory, then open the local url on the browser to check real-time appearance of website while editing.
** Global configurations
   The global configuration is done using files in [[./config/_default/][this directory]]. Particularly:

   [[./config/_default/config.yaml][config.yaml]]: sets some global configuration of the website, especially the /tile/ of the webpage and the /baseURL/.

   [[./config/_default/menus.yaml][menus.yaml]]: sets the global menus of the websites. Each entry has a /name/, which is the string appears on the webpage menu. The webpage that the entry directing to is stored in a directory in /content/, whose name is specified in the /url/ property in [[./config/_default/menus.yaml][menus.yaml]]. The /weight/ of each entry in [[./config/_default/menus.yaml][menus.yaml]] determines the order of appearance of these menus ascendingly. More details can be found [[https://gohugo.io/variables/menus/][here]].

   [[./config/_default/languages.yaml][languages.yaml]]: sets the languages.
** Variables
   The variable 'weight' sets the order of appearance.
** Webpages appearances
*** Title and menu
    Title and menu appear on top of all web pages.

    Title can be set in the file [[./config/_default/config.yaml][config.yaml]] through the entry /tile/.

    Menu is set using the file [[./config/_default/menus.yaml][menus.yaml]]. Each entry has a /name/, which is the string appears on the webpage menu. The webpage that the entry directing to is stored in a directory in /content/, whose name is specified in the /url/ property in [[./config/_default/menus.yaml][menus.yaml]]. The /weight/ of each entry in [[./config/_default/menus.yaml][menus.yaml]] determines the order of appearance of these menus ascendingly. 
*** Home
    The main contents of home page is in directory [[./content/home/][home]]. The files are:

    [[./content/home/index.md][index.md]]

    [[./content/home/welcome.md][welcome.md]]: sets the welcome message and image that show up on top of the home page.

    [[./content/home/news.md][news.md]]: latest news from the group, whose content is in [[./content/news][news directory]]. The variable /count/ in /content/ entry determines the total number of news showing up on the home page. The /view/ variable in /design/ entry determines how much detail to show up here.

    [[./content/home/news.md][publications.md]]: recent publications from the group, whose content is in [[./content/publication][publications directory]]. The setting is similar to [[./content/home/news.md][news.md]].

    [[./content/home/cta.md][cta.md]]: buttons for quick access of certain contents.
*** Research
*** Publications    
**** Generating publications and authors from bibtex
     The /academic/ package provides a package to automatically generate both publication records and author profiles from bibtex file. To install the package, run /pip3 install -U academic/ on terminal. Then, go to the site root folder, put the bibtex entries of publications in /data/publications.bib/. Then, run /academic import --bibtex data/publications.bib/ at the same directory, and the publications and authors will be generated.

     For more details on the /academic/ command, see: [[https://github.com/wowchemy/hugo-academic-cli][https://github.com/wowchemy/hugo-academic-cli]].
*** News
    
    
   
